### ISSUE TITLE
New motor tab Save problems

### ISSUE THREAD

**Issue by Asizon** [betaflight/betaflight-configurator#2413] opened 2021-02-14 08:15 UTC
With the new motor tab save system, if user wrong check some option and then uncheck it, motor test, motor reorder and motor direction features doesnt work until you saved a non changed configuration.
To reproduce:
-Check some option and the uncheck
-See how features disappears
![image](https://user-images.githubusercontent.com/43983086/107871804-24251000-6ea5-11eb-9610-4c10e05aae6d.png)

**Comment by haslinghuis** [comment] 2021-02-14 14:28
This is by design. Change a setting and motor tests are disabled. To improve we could keep the state to avoid having to use Save and Reboot if nothing actual changed (after reverting a change).

**Comment by Asizon** [comment] 2021-02-17 06:13
Yes, i think if user reverts a change no need to reboot FC, it can be confusing with no changes:
![image](https://user-images.githubusercontent.com/43983086/108163615-a0129880-70ef-11eb-8a5e-5452c228baa2.png)

**Comment by Asizon** [comment] 2021-02-21 08:25
@haslinghuis Also note, that if you change to another FC, save problems persists in this fc from tthe previous fc and need to aplies non made changes in this FC.

**Comment by haslinghuis** [comment] 2021-02-23 00:23
`TABS.motors.isDirty` is initialized as false on entering the Motor tabs but it's retaining its value - after re-entering tab / reboot of FC? Restarting BFC does work. Resetting the isDirty flags to false in TABS.motors.initialize function solves this.

The question of changing a value and setting it back to initial will still have the isDirty flag raised. @chmelevskij does Vue has some state management dealing with this issue? 

https://css-tricks.com/build-a-state-management-system-with-vanilla-javascript/

**Comment by chmelevskij** [comment] 2021-02-23 05:37
Vue js or just plain js, it's a matter of dealing with changes properly IMO. This can be done with or without it.

It would be nice to move it to Vue, but in current state it's hard to move complex components. I've been sticking to tidy up modules and simple components for now. There is a quite a lot of global variables and actions going on, so it's hard to track these things.

**Comment by haslinghuis** [comment] 2021-03-05 01:38
Also fixed some UI design issues, the number of motors detected (still fails if a user select octo while having only 6 outputs (resources assigned). Had to change some variables because they were no valid key-pair key names. Fixed the flip-flopping of buttons by disabling where applicable.

**Comment by haslinghuis** [comment] 2021-03-06 20:18
@Asizon all should be fixed now.

- Fixed persisent behavior when changing settings. Further fixed some UI design issues (should look better on 1366 and 1920).
- Had to change some variables because they were no valid key-pair key names. 
- Fixed the flip-flopping of buttons by disabling where applicable.
- The number of motors detected is coming from models now (but still fails if a user select octo while having only 6 outputs (resources assigned)).

**Closed** 2021-03-22 12:57 UTC
