### ISSUE TITLE
Cannot uninstall betaflight

### ISSUE THREAD

**Issue by jon2912** [betaflight/betaflight-configurator#1855] opened 2020-01-10 07:37 UTC
It worked for a while, now cannot connect to my fc. I thought I'd reinstall betaflight, but when I try to uninstall I get 
Betaflight Configurator Uninstall
C:\Program Files [x86]\Betaflight\Betaflight-Configurator\uninbf00.dat not found, unable to perform uninstall. Manually delete files.
with a big X in a red circle.

**Comment by McGiverGim** [comment] 2020-01-10 07:56
Duplicated of https://github.com/betaflight/betaflight-configurator/issues/1854 take a look to the other thread, to see if it helps.

**Comment by mikeller** [comment] 2020-01-12 12:48
Duplicate of #1854.

**Closed by mikeller** 2020-01-12 12:48 UTC
Labels: duplicate
