### ISSUE TITLE
can't manually change PIDFs

### ISSUE THREAD

**Issue by mituritsyn** [betaflight/betaflight-configurator#2545] opened 2021-07-26 18:46 UTC
impossible to manually change PIDF coefficients in latest configurator;
Steps to reproduce:

- Manually change PIDF values, hit save button

expected behavior:
- new PIDF values are saved, sliders are hided

actual behavior:
- PIDF values changes are discarded, sliders still active

**Comment by haslinghuis** [comment] 2021-07-26 23:48
Duplicate of #2530

**Comment by haslinghuis** [comment] 2021-07-26 23:53
To be able to adjust PIDF manually you have to set `RPY` to `OFF`.

Design now is to use (firmware dictated) sliders (settings) first. Then put them OFF and adjust manually further if needed.

![image](https://user-images.githubusercontent.com/8344830/127073495-64fd1234-c58d-49f3-a7b9-00c7774c5abf.png)

**Comment by haslinghuis** [comment] 2021-07-27 00:02
We are considering to automatically disable the sliders upon changing settings manual.

**Closed** 2021-09-30 11:11 UTC
Labels: Pinned
