### ISSUE TITLE
Kernell error

### ISSUE THREAD

**Issue by bautert** [betaflight/betaflight-configurator#819] opened 2017-12-27 15:25 UTC
Windows Vista 32bit
Betaflight-Configurator 10.0.0

When running the executable the following error occurs.  Any suggestions?

"The procedure entry point QeryUnbiasedInterrupt Time could not be located in the dynamic link library KERNEL32.dll"

**Comment by mikeller** [comment] 2017-12-27 22:12
Duplicate of #813.

Essentially, since the toolkit we are using to build the standalone app with is based on Chrome, it can only run on platforms that are supported by recent versions of Chrome. Windows Vista 32bit is not one of them, sorry.

**Closed by mikeller** 2017-12-27 22:12 UTC
