### ISSUE TITLE
won't on stall on macOS Mojave 10.14.6 

### ISSUE THREAD

**Issue by S-T-A** [betaflight/betaflight-configurator#1721] opened 2019-10-06 19:44 UTC
i installed the latest configurator 6.0rc1 no problem and i installed 6.0rc2 and it rplaced 6.0rc1 with rc2 and i get this message when i try to open it  “Betaflight Configurator 4” is damaged and can’t be opened. You should move it to the Trash. 
There is nothing wrong with my mac it was just formatted and it's clean i deleated it and reinstalled rc1 again no problem if there is something i'm doing wrong id like to know cheers

Hardware Overview:

  Model Name:	MacBook Air
  Model Identifier:	MacBookAir6,2
  Processor Name:	Intel Core i7
  Processor Speed:	1.7 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB
  Boot ROM Version:	117.0.0.0.0

**Comment by IvoFPV** [comment] 2019-10-06 19:48
Please check other issues before opening yours. #1675 (comment) This seems to fix the issue for now. Could you try that?

**Comment by mikeller** [comment] 2019-10-07 00:25
Closing as duplicate of #1675.

**Closed by mikeller** 2019-10-07 00:25 UTC

**Comment by S-T-A** [comment] 2019-10-07 01:50
Alright cool I’ll give it a try thank you gentlemen 😎
