### ISSUE TITLE
"modes" and "OSD" tabs does not show any content

### ISSUE THREAD

**Issue by robomaniac** [betaflight/betaflight-configurator#1458] opened 2019-05-23 01:44 UTC
for some reason the "modes" tab does not show up in 10.5.1 and also the "OSD" tab.

I also tried 10.5.0

here is a picture
also, when I click the "modes" tab, I can't do anything else after that, I am stuck, can not click other tabs. I disconnect and reconnect to start over.
![modes_tabs_not_working](https://user-images.githubusercontent.com/5814871/58219466-08dd9e80-7cd9-11e9-9985-a6cc6db9f90a.png)

osd in 10.5.0
![osd](https://user-images.githubusercontent.com/5814871/58219641-a46f0f00-7cd9-11e9-8e9c-1422444529a6.png)

I am on win 7 pro, 64bit

similar issue as 1206 but it was on a MAC
https://github.com/betaflight/betaflight-configurator/issues/1206

**Comment by mikeller** [comment] 2019-05-23 01:49
Duplicate of #1356.

**Closed by mikeller** 2019-05-23 01:49 UTC
