### ISSUE TITLE
Receiver prevew screen; yaw direction goes to the wrong side.

### ISSUE THREAD

**Issue by mangoldc** [betaflight/betaflight-configurator#703] opened 2017-10-30 07:00 UTC
Yaw direction goes to the wrong side with reversed motor direction configuration.

**Comment by danybd** [comment] 2021-03-16 12:34
@mangoldc did you solve your trouble? Did you try the last releases?

**Comment by haslinghuis** [comment] 2021-03-23 11:40
Cannot reproduce. Please check you board and sensor alignment.

Looks like a configuration issue so please close the issue.

**Comment by McGiverGim** [comment] 2021-03-23 11:47
I think I will close this. Is from 2017. If the bug remains I think is better to open one issue new with more information.

**Closed by McGiverGim** 2021-03-23 11:47 UTC
Labels: bug
