### ISSUE TITLE
bug configurator 10.5.1 windows MODES

### ISSUE THREAD

**Issue by Vincentdt** [betaflight/betaflight-configurator#1369] opened 2019-04-12 19:50 UTC
Hello,

I'm stuck when i go to MODES i can only disconnect + i see nothing except ARM see the screen shot.
![image](https://user-images.githubusercontent.com/37982386/56062537-02204b00-5d6d-11e9-921a-aa1f53342167.png)

**Comment by McGiverGim** [comment] 2019-04-12 20:00
Look here https://github.com/betaflight/betaflight-configurator/issues/1365. Same problem.

**Comment by mikeller** [comment] 2019-04-14 07:54
@Vincentdt: Can you please specify what versions of configurator / firmware and what hardware you are using?

**Comment by oolcoo** [comment] 2019-04-15 18:47
> @Vincentdt: Can you please specify what versions of configurator / firmware and what hardware you are using?

same problem here with my trashcan

Configurator: 10.5.1 (10.5.0 same bug)
Firmware: BTFL 4.0.0
Target: CRAZYBEEF4FR

**Comment by McGiverGim** [comment] 2019-04-15 19:39
Exactly. The solution is to update to Betaflight 4.0 final from the Configurator.

**Comment by mikeller** [comment] 2019-04-16 18:25
Duplicate of #1362.

**Closed by mikeller** 2019-04-16 18:25 UTC

**Comment by Winky1st** [comment] 2019-05-07 13:16
Same here...but for a mobula7 with f3 board to update version is mostly impossible as wont work smooth unless loaded the stock 4.0 provided by them and than cant be loaded with configuratr 10.5.1 as per auxiliarttab issue
apologise for my not native English.

**Comment by Arvenz200** [comment] 2020-01-28 19:11
I am also having this same problem with the Modes tab with my new Trashcan. Luckily i had a backup copy i setup months ago when it was workign fine on my computer. Only i want to check what my settings are and lower Pids? So please help me with this? i have the latest Baseflight version. :(
