### ISSUE TITLE
Failsafe modification 

### ISSUE THREAD

**Issue by alex39292** [betaflight/betaflight-configurator#3866] opened 2024-03-30 22:29 UTC
### Is your feature request related to a problem? Please describe

When using the "landing" in Failsafe configuration page, I have to specify the time for the drone to descend.  But the drone may not have enough time and will simply turn off the motors without landing.

### Describe the solution you'd like

On flight controllers with a barometer installed, we can take changes in altitude data to determine whether the drone has landed or not.  I propose to add a radio button to the “Landing” tab: “Landing by barometer” and “Delay for turning off motors after landing” [10] seconds - i.e.  Altitude data does not change for [10 ]seconds.
![IMG_20240331_012718](https://github.com/betaflight/betaflight-configurator/assets/50744099/a29228e0-20df-4eed-aa01-55610ab7ff6e)

### Describe alternatives you've considered

We need to consider the best way for the real drone landing during the failsafe procedure.

**Comment by haslinghuis** [comment] 2024-03-30 22:42
See also https://github.com/betaflight/betaflight/issues/4663 :)

**Comment by alex39292** [comment] 2024-04-17 14:00
Yeah. I didn't see it ) The goal is to determine changes in baro data for example each 1 second ( changes in vertical speed). If no changes - our quad landed.

**Comment by haslinghuis** [comment] 2024-05-05 23:43
Duplicate of #4663

**Closed** 2024-05-05 23:44 UTC
Labels: Template: Feature Request
