### ISSUE TITLE
beta flight in Chinese how do I get English beta flight

### ISSUE THREAD

**Issue by chiefwc** [betaflight/betaflight-configurator#2450] opened 2021-03-21 17:46 UTC
# If your issue looks like a hardware fault or a configuration problem please don't raise an issue here.

## If you believe there is an issue with the firmware itself please follow these steps:
1. Describe your problem;
2. Include ways to reproduce the problem;
3. Provide as much information as possible about your hardware and software, including:
- what hardware / software you are using;
- the version of all the software used;
- how things are connected / wired up.
4. Remove this Text :).

**Comment by haslinghuis** [comment] 2021-03-21 17:49
At the bottom of the opening screen (do not connect) you can change language.

**Comment by haslinghuis** [comment] 2021-03-21 22:57
Duplicate of #2405

**Closed** 2021-03-22 12:52 UTC
Labels: duplicate
