### ISSUE TITLE
Failed to install 10.10.0-RC3 .deb on Ubuntu 23.10 because of dependencies

### ISSUE THREAD

**Issue by amatsumara** [betaflight/betaflight-configurator#3869] opened 2024-04-02 08:21 UTC
### Describe the bug

I downloaded latest release and was trying to install it:
```
dpkg -i betaflight-configurator_10.10.0-RC3_amd64.deb 
Selecting previously unselected package betaflight-configurator.
(Reading database ... 352261 files and directories currently installed.)
Preparing to unpack betaflight-configurator_10.10.0-RC3_amd64.deb ...
Unpacking betaflight-configurator (10.10.0-RC3) ...
dpkg: dependency problems prevent configuration of betaflight-configurator:
 betaflight-configurator depends on libgconf-2-4; however:
  Package libgconf-2-4 is not installed.

dpkg: error processing package betaflight-configurator (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 betaflight-configurator
```

### To Reproduce

Download [10.10.0-RC3](https://github.com/betaflight/betaflight-configurator/releases/tag/10.10.0-RC3) .deb package from releases section. Run:
`dpkg -i betaflight-configurator_10.10.0-RC3_amd64.deb`

### Expected behavior

At least .deb linked to existing Ubuntu package so it is possible to install it but there none:
```
apt search libgconf-2-4
Sorting... Done
Full Text Search... Done
```

### Configurator version

10.10.0-RC3

**Comment by haslinghuis** [comment] 2024-04-02 10:15
Please check [README](https://github.com/betaflight/betaflight-configurator?tab=readme-ov-file#linux-users)

**Comment by haslinghuis** [comment] 2024-04-02 15:16
Specific

> The libatomic library must also be installed before installing Betaflight Configurator. (If the library is missing, the installation will succeed but Betaflight Configurator will not start.) Some Linux distributions (e.g. Fedora) will install it automatically. On Debian or Ubuntu you can install it as follows:
```
sudo apt install libatomic1

```

**Comment by McGiverGim** [comment] 2024-04-03 10:44
I'm more a windows user, so I don't know if I understand exactly the issue, but the dependencies, must be installed automatically:

https://github.com/betaflight/betaflight-configurator/blob/eb8f3986c54e697bda1dc795db177312308ca940/gulpfile.js#L802

the problem is that dpkg doesn't do that. You must install the dependencies by hand. Nothing we can do with it as far as I know.

**Comment by nerdCopter** [comment] 2024-04-03 13:04
- this is basically a duplicate of: https://github.com/betaflight/betaflight-configurator/issues/3860
- solutions there as well.

**Comment by haslinghuis** [comment] 2024-04-03 13:59
See: https://2h3ph3rd.medium.com/how-to-install-libgconf-2-4-on-ubuntu-23-10-fec6bda8d5f5

**Comment by amatsumara** [comment] 2024-04-03 14:03
> * this is basically a duplicate of: [No response after launching betaflight configurator #3860](https://github.com/betaflight/betaflight-configurator/issues/3860)
> 
>     * solutions there as well.

There is no information of Ubuntu version used in that issue. **libatomic1** installed already in Ubuntu 23.10. 
**apt install -f** last lines output:
```
The following packages have unmet dependencies:
 betaflight-configurator : Depends: libgconf-2-4 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
**libgconf-2-4** can't be found in Ubuntu 23.10 repos.

**Comment by nerdCopter** [comment] 2024-04-03 14:12
Thanks for clarification @amatsumara , apologies for my not understanding Ubuntu 23.x has updated libraries.

**Comment by nerdCopter** [comment] 2024-04-03 16:15
i was able to remove `libgconf-2-4` as a dependency in the gulpfile.js, and install into a fresh Xubuntu 23.10 VM.
i did not test removing `libatomic1`.
further testing should be done on legacy systems i suppose.

**Comment by haslinghuis** [comment] 2024-04-03 19:50
libgconf-2-4: This package is for legacy applications and no longer used by GNOME. [Link](https://packages.debian.org/buster/libgconf-2-4)

Agree we might to keep this in for backwards compatibility.

**Comment by haslinghuis** [comment] 2024-04-04 15:33
Afaik Betaflight does only support LTS versions of [Ubuntu](https://wiki.ubuntu.com/Releases)

The missing package could be installed using https://2h3ph3rd.medium.com/how-to-install-libgconf-2-4-on-ubuntu-23-10-fec6bda8d5f5 as guess we need to keep it for Ubuntu 20.04 LTS for at least one year.

**Comment by nerdCopter** [comment] 2024-04-04 15:35
Good choice. I also use only LTS. If it can be gated in some way, such would be the way to go.

**Comment by amatsumara** [comment] 2024-04-04 20:21
> Afaik Betaflight does only support LTS versions of [Ubuntu](https://wiki.ubuntu.com/Releases)
> 
> The missing package could be installed using https://2h3ph3rd.medium.com/how-to-install-libgconf-2-4-on-ubuntu-23-10-fec6bda8d5f5 as guess we need to keep it for Ubuntu 20.04 LTS for at least one year.

Do you think all will work well in Ubuntu 24.04 LTS Noble Numbat (should be released in April 2024)? Will try it.

Yeah, installing Debian repos should work.

**Comment by haslinghuis** [comment] 2024-04-04 20:25
We will check next LTS version after release.

**Comment by vitali2y** [comment] 2024-04-07 21:20
Yeah, [this recept](https://gist.github.com/vitali2y/950bc3ad341b5a602c0a97cac346ca80) works as a charm @ _Linux Mint 21.2_.

**Closed** 2024-04-09 19:53 UTC
Labels: Template: Bug
