### ISSUE TITLE
Motors go to 100% when pressing END key 

### ISSUE THREAD

**Issue by dhxfpv** [betaflight/betaflight-configurator#2745] opened 2022-01-09 10:45 UTC
### Describe the bug
POS1 and END button on the keyboard are reversed. END makes 100% Throttle and POS1 makes 0% Throttle 

### To Reproduce
in the Motor Tab enable arming and drag a motorslider to any value. than press END it will go to 100% throttle.

### Expected behavior
END will normaly stop the motors and POS1 will make them spin 100% 

### Setup

- Configurator version: 10.8.0

```
PASTE THE OUTPUT OF 'diff' HERE
```diff all

# version
# Betaflight / STM32F7X2 (S7X2) 4.3.0 Jan  9 2022 / 11:51:40 (ee8560af4) MSP API: 1.44
# config: manufacturer_id: DIAT, board_name: MAMBAF722_I2C, version: ec268d11, date: 2021-07-26T13:10:45Z

# start the command batch
batch start

# reset configuration to default settings
defaults nosave

board_name MAMBAF722_I2C
manufacturer_id DIAT
mcu_id 003400355632501720323236
signature 

# name: DHX 2

# resources
resource MOTOR 1 A08
resource MOTOR 2 A09
resource MOTOR 3 C08
resource MOTOR 4 C09

# serial
serial 2 2048 115200 57600 0 115200
serial 3 16384 115200 57600 0 115200

# beacon
beacon RX_SET

# aux
aux 0 0 0 1700 2100 0 0
aux 1 13 2 1950 2075 0 0
aux 2 35 1 1875 2100 0 0
aux 3 49 2 1150 1225 0 0

# vtxtable
vtxtable bands 5
vtxtable channels 8
vtxtable band 1 BOSCAM_A A FACTORY 5865 5845 5825 5805 5785 5765 5745 5725
vtxtable band 2 BOSCAM_B B FACTORY 5733 5752 5771 5790 5809 5828 5847 5866
vtxtable band 3 BOSCAM_E E FACTORY 5705 5685 5665 5645 5885 5905 5925 5945
vtxtable band 4 FATSHARK F FACTORY 5740 5760 5780 5800 5820 5840 5860 5880
vtxtable band 5 RACEBAND R FACTORY 5658 5695 5732 5769 5806 5843 5880 5917
vtxtable powerlevels 3
vtxtable powervalues 13 20 26
vtxtable powerlabels 25 100 400

# master
set dyn_notch_count = 1
set dyn_notch_q = 500
set acc_hardware = NONE
set acc_calibration = -35,35,17,1
set baro_hardware = NONE
set min_check = 1020
set max_check = 1990
set serialrx_provider = CRSF
set dshot_bidir = ON
set failsafe_delay = 6
set vbat_scale = 111
set yaw_motors_reversed = ON
set small_angle = 180
set report_cell_voltage = ON
set osd_warn_batt_warning = OFF
set osd_warn_visual_beeper = OFF
set osd_alt_alarm = 1000
set osd_tim2 = 1
set osd_link_quality_pos = 2444
set osd_tim_2_pos = 2401
set osd_vtx_channel_pos = 2433
set osd_current_pos = 2453
set osd_mah_drawn_pos = 2411
set osd_altitude_pos = 2080
set osd_warnings_pos = 14633
set osd_avg_cell_voltage_pos = 2379
set osd_flip_arrow_pos = 2253
set osd_stat_tim_2 = OFF
set osd_stat_max_spd = OFF
set osd_stat_endbatt = ON
set osd_stat_max_alt = ON
set osd_stat_bbox = OFF
set osd_stat_bb_no = OFF
set osd_stat_max_g_force = ON
set vtx_band = 5
set vtx_channel = 4
set vtx_power = 1
set vtx_freq = 5769
set vcd_video_system = NTSC
set gyro_1_align_yaw = 1800
set name = DHX 2

profile 0

# profile 0
set pidsum_limit = 1000
set pidsum_limit_yaw = 1000
set feedforward_averaging = 2_POINT
set feedforward_smooth_factor = 65
set feedforward_jitter_factor = 4

profile 1

profile 2

# restore original profile selection
profile 0

rateprofile 0

# rateprofile 0
set roll_rc_rate = 26
set pitch_rc_rate = 23
set yaw_rc_rate = 22
set roll_expo = 32
set pitch_expo = 33
set yaw_expo = 47
set roll_srate = 55
set pitch_srate = 53
set yaw_srate = 49

rateprofile 1

# rateprofile 1
set rates_type = BETAFLIGHT
set roll_rc_rate = 80
set pitch_rc_rate = 80
set yaw_rc_rate = 80
set roll_srate = 70
set pitch_srate = 70
set yaw_srate = 70

rateprofile 2

# rateprofile 2
set rates_type = BETAFLIGHT
set roll_rc_rate = 100
set pitch_rc_rate = 100
set yaw_rc_rate = 100
set roll_expo = 1
set pitch_expo = 1
set yaw_expo = 1
set roll_srate = 59
set pitch_srate = 59
set yaw_srate = 59

rateprofile 3

# rateprofile 3
set rates_type = BETAFLIGHT
set roll_rc_rate = 112
set pitch_rc_rate = 90
set yaw_rc_rate = 80
set roll_srate = 70
set pitch_srate = 70
set yaw_srate = 70

rateprofile 4

rateprofile 5

# restore original rateprofile selection
rateprofile 1

# save configuration
save
# 

<!-- Add any other context about the problem that you think might be relevant here. -->

**Comment by haslinghuis** [comment] 2022-01-09 15:23
Duplicate of https://github.com/betaflight/betaflight-configurator/issues/2528

**Closed** 2022-01-18 21:59 UTC
