### ISSUE TITLE
AT32 on Mac big issue 

### ISSUE THREAD

**Issue by andreagovons** [betaflight/betaflight-configurator#3776] opened 2024-01-27 11:30 UTC
### Describe the bug

Betaflight 10.10.0 rc1 work perfectly with stm32 on Mac, 
but when I plug flight controller AT32 I can't do nothing can read everything but if I want just activate different uart doesn't do nothing! I need to compile all the setting with CLI 
even motor tab is not working 

### To Reproduce

.

### Expected behavior

.

### Configurator version

10.10.0 RC1

**Comment by haslinghuis** [comment] 2024-01-27 11:56
Please do not open duplicate issue reports.

Duplicate of #3514

**Closed by haslinghuis** 2024-01-27 11:56 UTC
Labels: Template: Bug
