### ISSUE TITLE
On 10.9.0 (697943b), Adding BLACKBOX to custom defines has no effect

### ISSUE THREAD

**Issue by void-spark** [betaflight/betaflight-configurator#3461] opened 2023-05-22 06:15 UTC
### Describe the bug

Open Betaflight configuration
Go to Options
Verify Permanently enable export mode is on.
Go to Firmware Flasher
Select board (MATEKF4111RX)
Select firmware version (4.4.1)
(No advanced options show (No Custom Defines / Select commit), reported in other issue)
Switch back to Options
Switch back to Firmware Flasher, now the advanced options show
Under Custom Defines, add 'BLACKBOX'.
Click Load firmware(online).
Click on the build log, it does not show USE_BLACKBOX, in fact it will pull the cache of the same build without 'BLACKBOX'.
From the log:
"make MATEKF411RX EXTRA_FLAGS="-D'BUILD_KEY=da3036bea29adab62ac9719c7a77e688' -D'RELEASE_NAME=4.4.1' -DCLOUD_BUILD -DUSE_DSHOT -DUSE_GPS -DUSE_GPS_PLUS_CODES -DUSE_LED_STRIP -DUSE_OSD -DUSE_OSD_HD -DUSE_OSD_SD -DUSE_PINIO -DUSE_SERIALRX -DUSE_SERIALRX_CRSF -DUSE_SERIALRX_DEFAULT -DUSE_SERIALRX_GHST -DUSE_SERIALRX_SBUS -DUSE_TELEMETRY -DUSE_TELEMETRY_CRSF -DUSE_TELEMETRY_GHST -DUSE_VTX""

### To Reproduce

See description

### Expected behavior

Adding 'BLACKBOX' under Custom Defines, should build with blackbox support.
Actually, why is this not a option under 'Other options' ?

### Configurator version

10.9.0

### Flight controller configuration

```txt
Not relevant
```

**Comment by haslinghuis** [comment] 2023-05-22 11:35
@duplicate of #3460

**Closed by haslinghuis** 2023-05-22 11:35 UTC
Labels: Template: Bug
