### ISSUE TITLE
RunCam Split V2 commands not working

### ISSUE THREAD

**Issue by estevanb** [betaflight/betaflight-configurator#1066] opened 2018-06-20 03:16 UTC
I am using Matek F722D, Betaflight 3.4 RC2. RunCam Split 2 commands stopped working. Can´t initiate recording.

**Comment by mikeller** [comment] 2018-06-20 08:15
This is not a configurator issue. Also, it is most likely a duplicate of betaflight/betaflight#5832.

**Closed by mikeller** 2018-06-20 08:15 UTC
