### ISSUE TITLE
Sliders disabled while only moving/changing sliders?

### ISSUE THREAD

**Issue by audiogek** [betaflight/betaflight-configurator#2530] opened 2021-07-02 18:43 UTC
At following slider setting(see pic), sliders are disabled when saved, and BF configurator thinks I set the pid numbers manually.
I only moved the sliders and did not change any number manually.
This is on 4.2.9 and 10.7

![Screenshot 2021-07-02 203414](https://user-images.githubusercontent.com/68812769/124316642-34007080-db76-11eb-93e9-f8f543f8e457.png)

**Comment by haslinghuis** [comment] 2021-07-02 21:27
Cannot reproduce with 4.2.9 firmare on 10.7 or 10.8. I have fixed this behavior on 10.8 but have not worked on 10.7, only difference I notice in the screenshot is Derivative is separated as Dmax and Dmin.

![Screenshot from 2021-07-02 23-11-39](https://user-images.githubusercontent.com/8344830/124328975-e8a48d00-db8a-11eb-8814-cada55542b3d.png)

![Screenshot from 2021-07-02 23-14-05](https://user-images.githubusercontent.com/8344830/124329168-476a0680-db8b-11eb-80cb-1097488e6528.png)

**Comment by audiogek** [comment] 2021-07-02 22:19
> Cannot reproduce with 4.2.9 firmare on 10.7 or 10.8. I have fixed this behavior on 10.8 but have not worked on 10.7, only difference I notice in the screenshot is Derivative is separated as Dmax and Dmin.
>

And when you uncheck D-min?

**Comment by haslinghuis** [comment] 2021-07-02 22:49
Yes with 4.2.9 on 10.7 / 10.8 or 4.3 on 10.8 all suffer from Dmin being disabled.

**Comment by haslinghuis** [comment] 2021-07-02 22:55
@IllusionFpv as calculation in 4.3 is done in firmware now, does it take dmin setting in account?

**Comment by audiogek** [comment] 2021-07-03 08:52
> Yes with 4.2.9 on 10.7 / 10.8 or 4.3 on 10.8 all suffer from Dmin being disabled 😞

I was asking: Can you reproduce the bug I mentioned with d-min disabled?

Or do you mean you already solved this for 4.3?

**Comment by haslinghuis** [comment] 2021-07-03 12:21
No. I meant to say I can reproduce the problem. Firmware 4.3 introduces a new set of sliders which is still being worked on. Raised this issue with the team.

**Comment by audiogek** [comment] 2021-07-03 13:53
So this is basically soved. Nice, thanks!

**Comment by Asizon** [comment] 2021-07-04 08:08
Fixed in https://github.com/betaflight/betaflight/pull/9119

**Closed by Asizon** 2021-07-04 08:08 UTC
