### ISSUE TITLE
Backup button fail if model name has ascii chars

### ISSUE THREAD

**Issue by Winky1st** [betaflight/betaflight-configurator#1226] opened 2018-11-08 18:32 UTC
Hi, I apologize for my not native english.
BF configurator  version 10.4.0
I got mad today as the backup button was not working (not popping up the input window) . So I uninstalled it (full uninstall User app data too) and reinstalled it…. but no way, no luck.

At the end I discovered the issue : on model name I wrote modelname 5" ...well that " is the culprit.!!

Have fun and gorgeous flights.
ciao

**Comment by mikeller** [comment] 2018-11-10 00:16
@Winky1st: Yes, this is a known shortcoming of the framework that the configurator is built with. It has been discussed in #1050.

Duplicate of #461.

**Closed by mikeller** 2018-11-10 00:16 UTC
