### ISSUE TITLE
cant figure out why its not workinf

### ISSUE THREAD

**Issue by Steve-fpv92** [betaflight/betaflight-configurator#3022] opened 2022-09-16 23:19 UTC
### Describe the bug

says i need to update but i have the latest and it keeps downloading the same thibng can someone help im bad with online looking due to personal stuff. stoodley603@gmail.com

### To Reproduce

just uninstall then install but wont fix

### Expected behavior

help

### Configurator version

10.8.0

### Flight controller configuration

```txt
dji r1
```

### Add any other context about the problem that you think might be relevant here

please call or email stoodley603@gmail.com win 11 lenovo laptop

**Comment by Steve-fpv92** [comment] 2022-09-16 23:20
anyone who knows beta like a pro hmu plz lmk

**Comment by haslinghuis** [comment] 2022-09-16 23:25
Duplicate of https://github.com/betaflight/betaflight-configurator/issues/2986

**Closed by haslinghuis** 2022-09-16 23:25 UTC
Labels: Template: Bug
