### ISSUE TITLE
To be able to connect the apk by the Speedybee adapter

### ISSUE THREAD

**Issue by LoakAudio** [betaflight/betaflight-configurator#2723] opened 2021-12-30 18:22 UTC
### Is your feature request related to a problem? Please describe.
Depending on the generation of Android devices, multiple cables are needed to connect to a FC: USB C -> USB C, USB OTG + USB -> USB C, USB OTG + USB -> Micro USB. In addition USB OTG is not well implemented on every device (ex Fairphone or old Android devices)

### Describe the solution you'd like
Since it shows in Bluetooth list of all my devices, the Speedybee adapter seems to be an effective alternative to avoid cables and OTG, but I can't connect thru standard Bluetooth protocol. If the used protocol isn't proprietary, Can it be added to the rolling menu list of ports in the apk ?

### Describe alternatives you've considered
Continue to use a lot of cables

**Comment by Asizon** [comment] 2021-12-30 18:26
This is a feature request for future developments.

**Comment by LoakAudio** [comment] 2021-12-30 18:37
@Asizon ,
Yes, I understand that it is not a priority but in a more or less close future it would be interesting to be able to use Betaflight-Configurator by this device.

**Comment by haslinghuis** [comment] 2024-06-23 20:28
Duplicate of #3141

**Closed by haslinghuis** 2024-06-23 20:28 UTC
Labels: Feature Request
