### ISSUE TITLE
Stripped-Down PWA Version

### ISSUE THREAD

**Issue by realThirdpartycookie** [betaflight/betaflight-configurator#2968] opened 2022-07-04 15:03 UTC
### Is your feature request related to a problem? Please describe

Now that ExpressLRS has introduced WiFi to the masses of fpv drones, they included MSP over TCP. Apparently it works nice with the standard configurator for PCs.

### Describe the solution you'd like

So how nice would it be if there was a portable web app that would run on basically every hand-held device, even on closed source but widespread hardware like iPhones?

I’m not that experienced with programming but I saw that the BF configurator already uses JS and even has a Chrome app. So how difficult would it be to implement it as a PWA?

### Describe alternatives you've considered

Leave everything how it is, works nice as well without.

**Comment by haslinghuis** [comment] 2022-07-05 00:26
Duplicate of #2939

**Closed by haslinghuis** 2022-07-05 00:26 UTC
Labels: Template: Feature Request
