### ISSUE TITLE
Motor Tab Issues

### ISSUE THREAD

**Issue by windwardlefty** [betaflight/betaflight-configurator#3247] opened 2023-01-15 17:04 UTC
### Describe the bug

Struggling to get motor reorder to save properly and occasionally have to change motor direction a few times before it actually saves. Clicking the save button doesn't appear to do anything.   Even after enabling motor test mode function I am unable to actually test the motors at all

### To Reproduce

This was applied to a clean flash with full chip erase in classic flashing mode

### Expected behavior

Not have to change motor direction numerous times for it to work, have the ability to enable motor test mode and give me the option to spin the master slider or any of the singular motor sliders

### Configurator version

10.9 RC4

### Add any other context about the problem that you think might be relevant here

Definitely a configurator issue and not 4.4 RC4.  Tried a quad on 4.3.2 with 10.9 and same issue applies

**Comment by haslinghuis** [comment] 2023-01-15 18:11
Duplicate of #3244

**Closed by haslinghuis** 2023-01-15 18:11 UTC
Labels: Template: Bug
