### ISSUE TITLE
Copy rateprofile not working correctly

### ISSUE THREAD

**Issue by atshort** [betaflight/betaflight-configurator#1111] opened 2018-07-14 23:17 UTC
In configurator 10.3.1 on a Mac, on the PID tuning page, if I use the "copy rateprofile values" button while in rateprofile 2 and I say  "Copy values from current rateprofile to" rateprofile 3, what happens is rateprofile 1 is copied to rateprofile 3.

**Comment by mikeller** [comment] 2018-07-14 23:23
@atshort: At least in your statement you are mixing 'profile' and 'rateprofile'. These are different and independent things. Could it be that you are mixing this up?

**Comment by atshort** [comment] 2018-07-14 23:28
Sorry, I meant rateprofile 2. All of the above took place in profile 1. I just corrected it.

**Comment by mikeller** [comment] 2018-07-14 23:33
@basdelfos: Do you have time to look into this?

**Comment by richard-scott** [comment] 2018-07-16 08:05
In my experience with this you need to click "save" straight after copying a profile. You need to click save before looking at the target profile, otherwise the board settings are loaded for that target profile from the FC and it "looks" like the function didn't work... Maybe the copy feature could be setup to save automatically?

**Comment by basdelfos** [comment] 2018-07-16 08:55
I will have to look into this issue in the coming days.
From what I remember, I think that Richard is right. The function copies the rate-profile struct from one profile to the other profile. Hitting save will store the profile into the EEPROM. But I will have to dig into this to confirm this is the case.

**Comment by atshort** [comment] 2018-07-16 14:52
I am aware of the need to click save. Here are the steps to reproduce what I believe is the problem:

- wipe and flash flight controller
- in rateprofile 1, change something (I changed roll srate to 0.71), and click save
- switch to rateprofile 2, and click save
- click "Copy rateprofile values", and select from current rateprofile to rateprofile 3, then click save

I believe this should copy rateprofile 2 to rateprofile 3, but what I see is it copied rateprofile 1 to rateprofile 3.

**Comment by smoriarty21** [comment] 2018-07-16 22:04
@basdelfos @mikeller If you guys are busy and want me to take a crack at this one let me know.  I'd be happy to jump in and try to figure it out

**Comment by mikeller** [comment] 2018-07-17 01:05
@smoriarty21: Help is always appreciated.

@basdelfos: My suspicion is that this might be caused by interference with a rate profile switch set up on an adjustment range. If this is the case, and there is a valid RX signal, then the switch position is authoritative for the active rate profile on the flight controller, and the rate profile cannot be changed programatically by the configurator.

**Comment by atshort** [comment] 2018-07-17 02:22
Although I first noticed the problem in a working quad, the steps I outlined above to reproduce the problem were carried out on a bare flight controller (Bardwell F4), not connected to anything except USB. There's no RX in the picture, and as I mentioned I wiped the board and did a fresh install before testing so there are no adjustment ranges configured. I literally just performed the three steps outlined above on a freshly wiped/installed board.

**Comment by basdelfos** [comment] 2018-07-28 19:47
Sorry, I didn't found any time to take a look at this. All busy working and preparing for vacation. The next few weeks I can not fix this. I someone else sees time to fix this, please be my guest.

**Comment by smoriarty21** [comment] 2018-07-29 15:56
@mikeller Sounds good, Ill jump on this one after rc smoothing

**Comment by smoriarty21** [comment] 2018-08-21 23:56
@mikeller @etracer65 @McGiverGim 

I fixed the issue of the wrong rate profile being copied. While testing I noticed that profile 6 would not allow anything to be copied to it, dug through the code and put together a fix that worked on my LUXF4OSD.  This is my first time messing with the main betaflight repo so please excuse any mistakes :)

https://github.com/betaflight/betaflight/pull/6612
https://github.com/betaflight/betaflight-configurator/pull/1176

**Comment by atshort** [comment] 2018-08-22 01:41
Thank you.

**Comment by tavdog** [comment] 2018-09-11 08:11
I'm seeing this bug on my Matek F405 , BF 3.5.1, mac configurator 10.4.0. When trying to copy rate profile #1 to rate profile #2, nothing happens. I've tried a save before going to rate profile #2 but the default rates persist.  This board is un upgrade from 3.3.3 to 3.5.1 with settings moved over via diff.

**Comment by McGiverGim** [comment] 2019-04-03 10:49
It seems fixed by #1176 and betaflight/betaflight#6612. I close this.

**Closed by McGiverGim** 2019-04-03 10:49 UTC
Labels: bug
