### ISSUE TITLE
10.3.0 Pixels not detected correctly with custom OSD logo

### ISSUE THREAD

**Issue by HaroldStash** [betaflight/betaflight-configurator#1077] opened 2018-06-24 05:58 UTC
I attempted making my own OSD logo and the colors are not being detected correctly. 

I have tried using this image and it doesn't work. 

![untitled-1](https://user-images.githubusercontent.com/4766749/41816387-dcd07dfe-7738-11e8-96a5-4e877ea3bc46.png)

**Comment by McGiverGim** [comment] 2018-06-28 09:35
This image has some pixels that are a mix between green and white, for example in the "BETA" letters limits, between black and green in the wasp limits, etc.

You must only use pure black, white and green, nothing more.

@atomgomba can you confirm this?

**Comment by mikeller** [comment] 2018-06-28 10:49
I can confirm this. After testing this functionality, and struggling to create an image that is accepted, I think there is room for improvement. I think if we changed the processing to use black (#000000) as black, white (#ffffff) as white, and everything else as transparent it would become easier for users to use, without losing any functionality. What do you think, @atomgomba?

**Comment by atomgomba** [comment] 2018-06-28 12:14
There is a green pixel on the image of color `rgb(0, 227, 0)` (`#00E300`). I think these kind of errors stem in the fact that the used image editor is not suited or properly set up for pixel art. For instance it's doing anti-aliasing, "optimize" the palette or what not. I think I'm going to add the hex code and coordinates of the wrong pixel detected to the error message.

**Comment by McGiverGim** [comment] 2018-07-12 07:36
This was fixed in https://github.com/betaflight/betaflight-configurator/pull/1101 but I left this open because the suggestion of mikeller I think is a good idea. Maybe in a future can be implemented.

**Comment by haslinghuis** [comment] 2024-05-06 00:57
Closing as fixed in #1101 and stale request.

**Closed by haslinghuis** 2024-05-06 00:57 UTC
Labels: Feature Request
