### ISSUE TITLE
GPS status icon does not illuminate orange when GPS is connected

### ISSUE THREAD

**Issue by catphish** [betaflight/betaflight-configurator#3479] opened 2023-06-10 08:36 UTC
### Describe the bug

When a GPS device is connected and running, the GPS peripheral status indicator for GPS in the top-right of the configurator remains grey rather than turning orange.
This can be seen in the screenshot in #3478 and on my own build:
![Screenshot at 2023-06-09 22-22-07](https://github.com/betaflight/betaflight-configurator/assets/9741/cd2f3c8b-ac86-4893-8c29-31bb73f21007)

### To Reproduce

Connect a current build of the configurator to a current build of betaflight. Connect and configure a GPS receiver.

### Expected behavior

The GPS status indicator should turn orange to indicate communication with a GPS device.

### Configurator version

10.10.0-debug-43f1558
I am running Betaflight 4.5.0 from git master: 7d7b6596b0839c1047704d29ae2a69aec015bd3e

**Comment by haslinghuis** [comment] 2023-06-10 10:37
Still works:

![image](https://github.com/betaflight/betaflight-configurator/assets/8344830/d3c9f049-53ec-4962-9edd-bed8475e0d0b)

![image](https://github.com/betaflight/betaflight-configurator/assets/8344830/9f78bba2-13f7-4967-9d6b-282a4d5b0731)

**Comment by Pancronos** [comment] 2023-06-12 17:44
Further tests:
1. BF doesn't crash even after long time i can still change tabs.
2. I tried 57600 no luck, Auto (reboots as 57600) both do not work # gps_info ># MON-VER acquired: false
3. After disconnecting usb for 2 minutes (my gps has no battery/memory)  almost immediatly got 3dfix, wonderful!!

**Comment by haslinghuis** [comment] 2023-06-12 19:19
Duplicate of #3478

**Closed by haslinghuis** 2023-06-12 19:19 UTC
Labels: Template: Bug
