### ISSUE TITLE
Configurator 10.9 Won't Load COM Port

### ISSUE THREAD

**Issue by dfayne** [betaflight/betaflight-configurator#3451] opened 2023-05-15 00:58 UTC
### Describe the bug

I am running Windows 11 Pro and can not get my flight controller to connect using 10.9.0 (697943b). Device Manager registers the Flight Controller as Betaflight STM32F7x2 in COM 3. When I open Configurator 10.9 the port drop down remains stuck at "Loading..," If I run the ImpulseRC Driver Fixer, it puts my FC into DFU mode and 10.9 will then recognize the COM port  in the Update Firmware screen. If I unplug the FC and plug it back in to kick it out of DFU, 10.9 no longer sees the port. Strangely, If I uninstall 10.9 and reinstall 10.8 I can connect with no issues. 
<img width="1179" alt="BFC10_8" src="https://github.com/betaflight/betaflight-configurator/assets/93413544/e71807ad-5e0a-4f32-8300-cd1766a49f26">
<img width="1188" alt="BFC10_9" src="https://github.com/betaflight/betaflight-configurator/assets/93413544/9c4e6882-eb5e-4abf-b130-7d841af09983">

### To Reproduce

Plug flight controller into a PC via USB C running Windows 11 Pro. 

### Expected behavior

Betaflight Configurator 10.9 Loads the COM port for the connected Flight Controller

### Configurator version

10.9.0 (697943b)

### Flight controller configuration

```txt
# version
# Betaflight / STM32F7X2 (S7X2) 4.3.0 Apr 15 2022 / 10:17:24 (9360ab1) MSP API: 1.44
# config: manufacturer_id: TMTR, board_name: TMPACERF7, version: c2b8c0d3, date: 2021-06-18T03:42:42Z

# start the command batch
batch start

board_name TMPACERF7
manufacturer_id TMTR

# name: Xing

# feature
feature -RX_PARALLEL_PWM
feature RX_SERIAL
feature TELEMETRY

# serial
serial 0 64 115200 57600 0 115200
serial 2 1 115200 57600 0 115200

# beeper
beeper -GYRO_CALIBRATED
beeper -RX_LOST_LANDING
beeper -ARMING_GPS_FIX
beeper -BAT_LOW
beeper -GPS_STATUS
beeper -ACC_CALIBRATION
beeper -ACC_CALIBRATION_FAIL
beeper -READY_BEEP
beeper -DISARM_REPEAT
beeper -ARMED
beeper -SYSTEM_INIT
beeper -ON_USB
beeper -BLACKBOX_ERASE
beeper -CRASH_FLIP
beeper -CAM_CONNECTION_OPEN
beeper -CAM_CONNECTION_CLOSE
beeper -RC_SMOOTHING_INIT_FAIL

# beacon
beacon RX_LOST
beacon RX_SET

# aux
aux 0 0 4 1825 2100 0 0
aux 1 1 0 1400 2100 0 0
aux 2 13 3 1850 2100 0 0
aux 3 35 2 1850 2100 0 0
aux 4 36 5 1775 2100 0 0

# rxrange
rxrange 0 988 2011
rxrange 1 988 2011
rxrange 2 988 2011
rxrange 3 988 2011

# master
set gyro_lpf1_static_hz = 0
set gyro_lpf2_static_hz = 600
set dyn_notch_count = 2
set dyn_notch_q = 400
set dyn_notch_min_hz = 90
set dyn_notch_max_hz = 800
set gyro_lpf1_dyn_min_hz = 0
set gyro_lpf1_dyn_max_hz = 0
set acc_calibration = -39,-42,-117,1
set mag_hardware = NONE
set baro_hardware = NONE
set mid_rc = 1501
set min_check = 1020
set rc_smoothing_auto_factor = 45
set rc_smoothing_auto_factor_throttle = 45
set serialrx_provider = CRSF
set min_throttle = 1070
set dshot_bidir = ON
set use_unsynced_pwm = OFF
set motor_pwm_protocol = DSHOT600
set motor_pwm_rate = 480
set bat_capacity = 1250
set yaw_motors_reversed = ON
set small_angle = 180
set deadband = 4
set simplified_gyro_filter_multiplier = 120
set osd_cap_alarm = 1000
set osd_alt_alarm = 400
set osd_rssi_pos = 6167
set osd_tim_2_pos = 266
set osd_remaining_time_estimate_pos = 299
set osd_current_pos = 6230
set osd_mah_drawn_pos = 6198
set osd_gps_speed_pos = 100
set osd_gps_lon_pos = 67
set osd_gps_lat_pos = 35
set osd_gps_sats_pos = 4
set osd_home_dir_pos = 9
set osd_home_dist_pos = 12
set osd_flight_dist_pos = 79
set osd_compass_bar_pos = 41
set osd_altitude_pos = 131
set osd_warnings_pos = 6569
set osd_avg_cell_voltage_pos = 6158
set osd_battery_usage_pos = 40
set osd_disarmed_pos = 6539
set osd_nvario_pos = 164
set osd_rtc_date_time_pos = 8
set rate_6pos_switch = ON
set rpm_filter_q = 1000
set rpm_filter_fade_range_hz = 100
set name = Xing

profile 0

# profile 0
set dterm_lpf1_dyn_min_hz = 0
set dterm_lpf1_dyn_max_hz = 0
set dterm_lpf1_dyn_expo = 0
set dterm_lpf1_static_hz = 105
set dterm_lpf2_static_hz = 210
set anti_gravity_gain = 5000
set p_pitch = 59
set i_pitch = 90
set d_pitch = 33
set f_pitch = 137
set p_roll = 54
set i_roll = 82
set d_roll = 29
set f_roll = 125
set p_yaw = 54
set i_yaw = 82
set f_yaw = 125
set d_min_roll = 29
set d_min_pitch = 33
set feedforward_averaging = 2_POINT
set feedforward_smooth_factor = 35
set feedforward_jitter_factor = 4
set feedforward_boost = 18
set simplified_master_multiplier = 110
set simplified_i_gain = 85
set simplified_d_gain = 90
set simplified_pi_gain = 110
set simplified_dmax_gain = 0
set simplified_feedforward_gain = 95
set simplified_pitch_pi_gain = 105
set simplified_dterm_filter_multiplier = 140

rateprofile 0

# rateprofile 0
set roll_rc_rate = 2
set pitch_rc_rate = 2
set yaw_rc_rate = 2
set roll_expo = 40
set pitch_expo = 40
set yaw_expo = 40
set roll_srate = 80
set pitch_srate = 80
set yaw_srate = 60

# end the command batch
batch end
```

**Comment by haslinghuis** [comment] 2023-05-15 01:05
Duplicate of #3443

**Closed by haslinghuis** 2023-05-15 01:05 UTC
Labels: Template: Bug
