### ISSUE TITLE
Feature Request: Add Profile selection on Adjustments

### ISSUE THREAD

**Issue by mizuta1951** [betaflight/betaflight-configurator#960] opened 2018-03-01 08:12 UTC
It is possible to change "Rate Profile" on inflight adjustments.
But the "Profle" is only able on stick command, which means your quad needs to be grounded.
It will be nice if you can change the Profile inflight.
This will give the possibility of changing preset PID's inflight.

**Comment by atomgomba** [comment] 2018-03-01 09:11
Related discussion: https://github.com/betaflight/betaflight/issues/2452

**Comment by mikeller** [comment] 2018-03-01 13:06
Duplicate of betaflight/betaflight#2452.

**Closed by mikeller** 2018-03-01 13:06 UTC
