### ISSUE TITLE
how to make arm64

### ISSUE THREAD

**Issue by jiaozhuliu** [betaflight/betaflight-configurator#4243] opened 2024-11-07 17:40 UTC
### Is your feature request related to a problem? Please describe

Hell i have Rockchip RK3588S new-gen 8-core 64-bit  Ubuntu 20.04 How to compile and use  

### Describe the solution you'd like

make erro

### Describe alternatives you've considered

Can an installation package be generated?

### Other information

https://github.com/user-attachments/assets/57446533-3a1d-4783-bfcd-7fe39baef66d

**Comment by nerdCopter** [comment] 2024-11-07 17:46
- inntallables are deprecated
- use https://app.betaflight.com

that said, maybe 
```
git checkout 10.10-maintenance
nvm use   #requires nvm installed
yarn install --check-files
yarn gulp release --armv8
```

**Comment by jiaozhuliu** [comment] 2024-11-11 14:50
The driver can be recognized, but the connection cannot be established.

**Comment by haslinghuis** [comment] 2024-12-10 00:17
Duplicate of #4247

**Closed by haslinghuis** 2024-12-10 00:17 UTC
Labels: Rejected Feature Request
