### ISSUE TITLE
betaflight configurator not installable on kubuntu 24.04

### ISSUE THREAD

**Issue by atazx** [betaflight/betaflight-configurator#4055] opened 2024-06-23 12:34 UTC
### Describe the bug

betaflight configurator not installable on kubuntu 24.04, unknow dependency error

### To Reproduce

try to install on kubuntu 24.04

### Expected behavior

installation works

### Configurator version

10.10

**Comment by haslinghuis** [comment] 2024-06-23 13:08
Duplicate of #3969

**Closed by haslinghuis** 2024-06-23 13:08 UTC
Labels: Template: Bug
