### ISSUE TITLE
Port Config impossible with config 10.4.0 and BFL 3.5.0

### ISSUE THREAD

**Issue by DeusAbsconditus** [betaflight/betaflight-configurator#1181] opened 2018-08-26 09:34 UTC
![grafik](https://user-images.githubusercontent.com/30833986/44626809-7794f380-a923-11e8-8963-25e12ae55c13.png)

Tried to reflash but no luck. Error message is telling "Firmware Update required! Serial Port Configuration with Firmware < 1.8.0 is not supported."

**Comment by mikeller** [comment] 2018-08-26 09:43
Duplicate of #1157.

**Closed by mikeller** 2018-08-26 09:43 UTC
