### ISSUE TITLE
A question about beginners

### ISSUE THREAD

**Issue by shackelton1978** [betaflight/betaflight-configurator#2180] opened 2020-09-22 03:21 UTC
# If your issue looks like a hardware fault or a configuration problem please don't raise an issue here.

## If you believe there is an issue with the firmware itself please follow these steps:
1. Describe your problem;
I am beginner for Developing the Hardware using Betaflight.
And reading the document ,i have a question is following 
  How to get the firmware for our own hardware to test ?
 how to configure the OSD 
Is there a document for the beginner ?

Best Regards & Thanks !
James Lee

**Comment by mikeller** [comment] 2020-09-22 13:42
1. Read up on 'internet etiquette', and stop cross-posting your requests;
2. Figure out what the right repository is to post your questions **before** posting them;
3. Read the instructions you are given when opening an issue **and follow them**.

Duplicate of betaflight/betaflight#10202

**Closed by mikeller** 2020-09-22 13:42 UTC
