### ISSUE TITLE
hmc5883l magnetometer 

### ISSUE THREAD

**Issue by spinorose** [betaflight/betaflight-configurator#3809] opened 2024-02-20 19:56 UTC
### Is your feature request related to a problem? Please describe

I went in the CLI to activate the compass and still cannot see it 

### Describe the solution you'd like

Can a prepopulated compass menu be made to make the whole experience easy and a details steps/documentation to activated .

### Describe alternatives you've considered

drop down menu in the software 

### Other information

I will be a good feature to allow more accuracy and less computing power .

**Comment by nerdCopter** [comment] 2024-02-20 20:09
- Some mag require LiPo power.
- Betaflight documentation was recently updated and may be of use. https://betaflight.com/docs/wiki/guides/current/Magnetometer
- Did you cloud-build with Magnetometers?
![image](https://github.com/betaflight/betaflight-configurator/assets/56646290/237b9989-9818-4232-a3ac-30fb3e847a71)

**Comment by spinorose** [comment] 2024-02-20 20:18
sure did 
![image](https://github.com/betaflight/betaflight-configurator/assets/7624406/c63d647e-bf82-4659-af1e-cb355c6dd12a)

**Comment by spinorose** [comment] 2024-02-20 20:21
I see information coming out is of the magnetometer  when I connect it using my Arduino to make sure is all working .

**Comment by haslinghuis** [comment] 2024-02-20 20:53
Closing as this is not an issue with configurator. Check status command in CLI.

Duplicate of https://github.com/betaflight/betaflight/issues/13338

**Closed by haslinghuis** 2024-02-20 20:53 UTC
Labels: Template: Feature Request

**Comment by spinorose** [comment] 2024-02-20 21:35
but my calibration tab is grayed out - so how do I calibrate it then

**Comment by haslinghuis** [comment] 2024-02-20 21:49
Please try our Discord server for support.

**Comment by spinorose** [comment] 2024-02-20 21:58
do you have the discord link

**Comment by haslinghuis** [comment] 2024-02-20 22:18
You can find the [link](https://discord.com/invite/gV4XSq3fus) on the landing page of configurator.
