### ISSUE TITLE
Add FLASH on LUXF7HDV

### ISSUE THREAD

**Issue by martukas0210** [betaflight/betaflight-configurator#3291] opened 2023-01-29 21:12 UTC
### Describe the bug

No option to do blackbox because no flash on custom build even have selected FLASH option. Flash appears on core only build.

### To Reproduce

Use cloud build options and select option "FLASH"

### Expected behavior

The onboard data flash chip should be available.

### Configurator version

10.9

### Flight controller configuration

```txt
# status (after custom defines: FLASH_M25P16)
MCU F722 Clock=216MHz, Vref=3.28V, Core temp=44degC
Stack size: 2048, Stack address: 0x20010000
Configuration: CONFIGURED, size: 2920, max available: 16384
Devices detected: SPI:1, I2C:0
Gyros detected: gyro 1
GYRO=MPU6000, ACC=MPU6000
OSD: MSP (60 x 22)
BUILD KEY: 940e0afe2f89bdcd1fc14a6a76f8a474 (4.4.0)
System Uptime: 486 seconds, Current Time: 2023-01-29T21:05:55.384+00:00
CPU:54%, cycle time: 125, GYRO rate: 8000, RX rate: 15, System rate: 9
Voltage: 13 * 0.01V (0S battery - NOT PRESENT)
I2C Errors: 0
FLASH: JEDEC ID=0x00ef4018 16M
Arming disable flags: RXLOSS CLI MSP RPMFILTER

# status (with FLASH option without custom defines)
MCU F722 Clock=216MHz, Vref=3.28V, Core temp=41degC
Stack size: 2048, Stack address: 0x20010000
Configuration: CONFIGURED, size: 3592, max available: 16384
Devices detected: SPI:1, I2C:0
Gyros detected: gyro 1
GYRO=MPU6000, ACC=MPU6000
OSD: NONE (238 x 48)
BUILD KEY: 717a90377c838299cbd2a409cc911d19 (4.4.0)
System Uptime: 12 seconds, Current Time: 2023-01-29T21:09:49.682+00:00
CPU:28%, cycle time: 125, GYRO rate: 8000, RX rate: 15, System rate: 9
Voltage: 15 * 0.01V (0S battery - NOT PRESENT)
I2C Errors: 0
Arming disable flags: RXLOSS CLI MSP MOTOR_PROTO
```

**Comment by haslinghuis** [comment] 2023-01-29 21:57
Duplicate of https://github.com/betaflight/unified-targets/issues/851

**Closed by haslinghuis** 2023-01-29 21:57 UTC
Labels: Template: Bug
