### ISSUE TITLE
OSD Snapping Issue

### ISSUE THREAD

**Issue by handcraftedcc** [betaflight/betaflight-configurator#4204] opened 2024-10-07 16:25 UTC
### Describe the bug

On betaflight configurator 10.10.0 in PAL mode, the way the snapping grid is laid out you cannot center any element directly in the screen (crosshairs etc) since the grid is an even number of spots, and thus the is no center row/column. So while you can put the crosshairs just to the right/left/above/below the center you can't truly center it.
![Screenshot 2024-10-07 112216](https://github.com/user-attachments/assets/6ee1a0c5-d318-471d-851b-d118b939d0c7)

### To Reproduce

Open Betaflight 10.10.0 (Firmware is 4.4.0) and on OSD menu, set to PAL attempt to center the crosshairs.

### Expected behavior

Have an odd number of grid elements so that you can perfectly center items in the screen.

### Configurator version

10.10.0

### Flight controller configuration

```txt
# version
# Betaflight / STM32F405 (S405) 4.4.0 Oct  6 2024 / 03:49:06 (4605309d8) MSP API: 1.45

# config: YES

# start the command batch
batch start

board_name CLRACINGF4
manufacturer_id CLRA

# feature
feature RSSI_ADC

# serial
serial 0 64 115200 57600 0 115200
serial 2 32 115200 57600 0 115200
serial 3 2048 115200 57600 0 115200

# beacon
beacon RX_LOST
beacon RX_SET

# aux
aux 0 0 0 1700 2100 0 0
aux 1 1 2 1300 1700 0 0
aux 2 2 2 1700 2100 0 0
aux 3 27 3 1700 2100 1 0
aux 4 27 5 1700 2100 1 0
aux 5 13 4 1700 2100 0 0
aux 6 35 1 1700 2100 0 0

# master
set acc_calibration = -12,-19,-68,1
set serialrx_provider = SBUS
set osd_vbat_pos = 2433
set osd_tim_1_pos = 2486
set osd_tim_2_pos = 2518
set osd_remaining_time_estimate_pos = 439
set osd_flymode_pos = 2105
set osd_crosshairs_pos = 2286
set osd_ah_sbar_pos = 238
set osd_ah_pos = 110
set osd_current_pos = 2465
set osd_mah_drawn_pos = 2497
set osd_warnings_pos = 14793
set osd_disarmed_pos = 2091
set vcd_video_system = PAL

profile 0

# profile 0
set tpa_rate = 67

rateprofile 0

# end the command batch
batch end
```

**Comment by haslinghuis** [comment] 2024-10-07 16:33
duplicate of #3535

**Closed** 2024-10-07 16:34 UTC
Labels: Template: Bug
