### ISSUE TITLE
BFC highly unstable on Mac

### ISSUE THREAD

**Issue by MadAEng** [betaflight/betaflight-configurator#2506] opened 2021-06-08 21:51 UTC
I'm using 10.7 on my 2020 Macbook running Big Sur, but it is highly unstable.
Upon reboot it will auto connect, however, that's the only thing I know for sure, if I disconnect in any way through reboot or unplug-replug, it's a coin flip if BFC will connect to my FC again. If it doesn't, I'll most likely have to reboot again.
On some occasions, BFC will just completely shut down out of the blue.
If I restart BFC, most of the time, it still won't connect.
I'm having the same issues on several FC's, and whilst setting up a new FC, it drives me absolutely up the wall. As far as I can tell, there are no warnings nor triggers that will cause it to happen, seems completely random.

**Comment by haslinghuis** [comment] 2021-06-08 21:56
Duplicate of https://github.com/betaflight/betaflight-configurator/issues/2274
Please try: https://github.com/betaflight/blackbox-log-viewer-nightlies

**Closed by haslinghuis** 2021-06-08 21:56 UTC
