### ISSUE TITLE
Beta flight latest release states corrupt file Mac OS

### ISSUE THREAD

**Issue by p925d** [betaflight/betaflight-configurator#1939] opened 2020-03-26 03:03 UTC
I downloaded the the latest release of Beta Flight to my 2019 MacBook Pro and upon installation a corrupt file message was displayed. I
Aborted and reloaded the file numerous times for the same message to appear. 

I have used earlier version of Betaflight on the MacBook prior to this issue. I have the latest version of Mac OS.

**Comment by p925d** [comment] 2020-03-26 04:21
Guys I’m not a coder, so I don’t know what would be considered missing. I have the latest release of 
macOS Catalina 10.15.4 and am trying to load BetaFlight 10.6.0 

Below is the image of the response received when I try to open the application. 

![0F71E5DA-1BCA-4F12-9653-79D8FAE64A89](https://user-images.githubusercontent.com/62682211/77609826-42290100-6ede-11ea-99da-b7c52308d04b.jpeg)

**Comment by mikeller** [comment] 2020-03-26 04:24
Thanks @p925d. The version numbers and exact error message go a long way.

**Comment by p925d** [comment] 2020-03-29 07:31
Mike, any updates on this instill cannot get the current version to download to the MacBook. So I loaded a older version which is working and updated to the latest firmware availed for my Emax mini magnum f4 stack. Another issue popped up that 1 motor will wind up and in addition when using BLHeli to read the ESC’s the system states that the ESC’s have been read but there is no data or settings to be displayed. 

Please advise. Thanks

**Comment by mikeller** [comment] 2020-03-29 08:57
Duplicate of #1675.

**Closed by mikeller** 2020-03-29 08:57 UTC
