### ISSUE TITLE
10.7 not opening correctly in Windows 10 64 bit

### ISSUE THREAD

**Issue by wdevine07** [betaflight/betaflight-configurator#2067] opened 2020-06-16 21:44 UTC
Updated to latest version, and it just opens to a black screen. The mouse cursor changes as if their may be items there, but I can't click anything. I've attached a screenshot. Fully updated windows 10 64 bit. 10.6 still runs fine.

![betaflight](https://user-images.githubusercontent.com/20910076/84831154-d2b44080-aff8-11ea-9e9d-afa14fd27df0.jpg)

**Comment by McGiverGim** [comment] 2020-06-17 06:37
Could you try with the `--disable-gpu` parameter as explained here: https://github.com/betaflight/betaflight-configurator/issues/2063 ?

**Comment by wdevine07** [comment] 2020-06-17 09:35
> Could you try with the `--disable-gpu` parameter as explained here: #2063 ?

That worked! Thank you.

**Comment by mikeller** [comment] 2020-06-21 03:31
Duplicate of #2063.

**Closed by mikeller** 2020-06-21 03:31 UTC
Labels: duplicate
