### ISSUE TITLE
Some boxes around Configurator are broken(empty)

### ISSUE THREAD

**Issue by Asizon** [betaflight/betaflight-configurator#2077] opened 2020-06-22 05:44 UTC
Betaflight 4.3 latest build
Configurator 10.8.0 latest build
Clean installation, no changes.
There are many checkbox boxes broken around the GUI, only appears checkbox button and the box is empty. Seems that it is happens after Jquery Update on PR https://github.com/betaflight/betaflight-configurator/pull/1995 . Here the first problem I can found:

![image](https://user-images.githubusercontent.com/43983086/85252434-07425500-b45c-11ea-95ef-40ee133d3329.png)

**Comment by McGiverGim** [comment] 2020-06-22 06:53
It seems something is going wrong in the `i18n.localizePage();` function. It makes the HTML elements disappear. I will play a little more with it...

**Comment by McGiverGim** [comment] 2020-06-22 07:33
I have found the reason... but not the origin...

The problem is that we have this code:
![image](https://user-images.githubusercontent.com/2673520/85260442-fa792d80-b46a-11ea-8ef1-292550fc84bc.png)

But for some reason, when loading the page the tags have moved INSIDE the first span tag:
![image](https://user-images.githubusercontent.com/2673520/85260528-1f6da080-b46b-11ea-81f7-5497fb3508e7.png)

The localize REPLACES all the contents of the tag, and this is the reason why it disappears.
The funny thing is that if I change slightly the tag:
![image](https://user-images.githubusercontent.com/2673520/85260671-52b02f80-b46b-11ea-825a-4f93e6711670.png)

This does not happen anymore. It works as before. 

And this only happens with the new JQuery. Maybe a bug in this version? Some idea?

**Comment by McGiverGim** [comment] 2020-06-22 07:36
Tested JQuery 3.5.1 without luck...

**Comment by Asizon** [comment] 2020-06-22 07:40
@McGiverGim seems that the reasson is here, on changes part:
https://jquery.com/upgrade-guide/3.5/

**Comment by McGiverGim** [comment] 2020-06-22 07:41
True... let's see what is the better workaround for this...

**Comment by McGiverGim** [comment] 2020-06-22 08:00
@mikeller the changelog of JQuery shows the possibility to use "temporary" a plugin to restore old behaviour, but I suppose the way to go is to change self-closing tags that never "must" be self-closing, like `div, span, p` to the no self-closing form. If not this will bite use later.
What do you think? Is the way to go?

**Comment by McGiverGim** [comment] 2020-06-22 08:40
Pushed a PR with the changes. It seems to make all working again, but maybe I missed some part...

**Comment by limonspb** [comment] 2020-06-28 01:30
Maybe a related thing?
PWM settings disappeared starting from 
`Bump jquery from 3.4.1 to 3.5.0`
![image](https://user-images.githubusercontent.com/2925027/85935314-edb66880-b8b4-11ea-8116-85d8cab2f8a0.png)

**Comment by Asizon** [comment] 2020-06-28 06:09
@limonspb yes, this bug is introduced by jquery update, it is already fixed but not yet merged

**Closed** 2020-06-28 06:56 UTC
Labels: bug
