### ISSUE TITLE
OSD: Reset Layout Option, Lost Elements after move in Preview

### ISSUE THREAD

**Issue by SnappyFPV** [betaflight/betaflight-configurator#218] opened 2016-08-13 18:47 UTC
Hi i use the Omnibus FC with integrated OSD.

I wish the GUI has a Layout Reset Button. Also some Elements that i have moved by mouse are disapeared in preview - can't see them anymore. Look in screenshot - timer is activated - not visible anymore after movement in preview.

![osd](https://cloud.githubusercontent.com/assets/6499781/17644950/1483701c-6197-11e6-95a9-a1f3a50ff49e.jpg)

**Comment by Tomcatt** [comment] 2016-08-16 10:23
So that's what the OSD section looks like.  I need to have a FC with an intergraded OSD on it in order to see this?  I thought my MinimOSD would work.

**Comment by nathantsoi** [comment] 2016-08-16 17:18
yes you need a board with a BFosd like: https://github.com/betaflight/betaflight/wiki/Board---OMNIBUS, mwosd is not supported, yet.

@SnappyFPV, i have fixed the lasted configurator (on master) to make it impossible to position an element off screen. if you need to reset the layout, use the "reset to defaults" on the other status or config page (I think that's where the button is?)

if that works for you, feel free to close this issue

**Comment by ksFPV** [comment] 2016-08-29 15:01
i also got the omnibus FC .. working with rc12 and latest Configurator.

I think the Problem is that if you drag something to the Betaflight Logo Area it's behind the logo and you won't be able to drag it arround anymore since the Logo is in Front.
I have this Problem with my CPU OSD .. it Shows in my Goggles but i can't move it anymore since the Logo is in front of it in the Configurator.

An Reset Switch or a Layer wich keeps your OSD Entrys up front would fix this i guess.

**Comment by nathantsoi** [comment] 2016-08-29 16:24
Good call. I'll add a reset button or a way to show hidden items. We used
to have the position shown as an integer value. Maybe we should bring that
back for now?

**Comment by ksFPV** [comment] 2016-08-29 16:31
maybe just combine the background Picture with the Logo itself and not the Logo as unmoveable object and it should work also i guess ... i'm not that deep into programming.. i just found that the logo is declared as unmovable Object somewhere in the code.

Or maybe an option to hide the logo (i think i've seen that in the Past or in CF Configurator somewhere)

**Comment by skaman82** [comment] 2016-08-29 16:53
I would remove the logo completely. It is not a positionable element.

Von meinem iPhone gesendet

**Comment by nathantsoi** [comment] 2016-09-23 14:27
It can be hidden now

**Closed by nathantsoi** 2016-09-23 14:27 UTC

**Comment by CheezeFPV** [comment] 2020-06-28 14:55
I have found this issue again.  I'm trying to add the "Mah Drawn" but when I turn the switch on nothing appears.

I've tried turning the "everything on" switch, that hasn't helped.

Is there an OSD reset somewhere?  Or will I have to completely reset the whole board? :(
