### ISSUE TITLE
turning off the "i understand risks" button in motors tab DOES NOT STOP motors spinning if 3d mode is setup.

### ISSUE THREAD

**Issue by Directory** [betaflight/betaflight-configurator#2571] opened 2021-08-19 05:25 UTC
In the motors tab, when a lipo is plugged in the esc and you try to move the sliders the motors will not spin because for safety you must first select the "i understand risks" button. normally if something out of control happens you can just turn off the toggle and the motors stop. The motors in my case do NOT stop spinning after turning off the toggle. This is especially problematic since my xt60's are stiff and it takes a lot of effort for me to yank out the battery on the bench with motors spinning. not a pleasant experience. I have only noticed this being a problem since i setup 3d mode. i am unaware if this is a configurator or firmware issue but im marking this issue under the configurator repo since this is where the gui toggle in question is not functioning.

**Comment by haslinghuis** [comment] 2021-08-19 20:10
With a 3D setup you will have to be extra careful so please take your props off before using!
 
Possible duplicate of https://github.com/betaflight/betaflight/issues/10267
Please see: https://github.com/betaflight/betaflight/wiki/3D-Setup

Have tested with latest nightly build of configurator and can't reproduce arming left enabled after disabling the motor test slider.

**Closed by haslinghuis** 2021-08-19 20:10 UTC
