### ISSUE TITLE
betaflight-configurator_10.8.0_amd64.deb version mismatch

### ISSUE THREAD

**Issue by RoGoR1** [betaflight/betaflight-configurator#2986] opened 2022-07-31 22:22 UTC
### Describe the bug

Most recently when I open betaflight-configurator it reports that I am using an out dated version. The version I have installed is 10.8.0, the version that is reporting is 10.7.2 on Debian bullseye 11.4.

betaflight-configurator_10.8.0_amd64.deb

# snap find betaflight-configurator
Name                     Version  Publisher  Notes  Summary
betaflight-configurator  10.7.2   ogra       -      Program and Control your BetaFlight FPV drones

snap refresh betaflight-configurator
snap "betaflight-configurator" has no updates available

![beta-fpv-10 8 0](https://user-images.githubusercontent.com/95770587/182047302-169d949c-f69b-445d-bc97-e9acd2dbf31d.png)

### To Reproduce

betaflight-configurator
![beta-fpv-10 8 0-warning2](https://user-images.githubusercontent.com/95770587/182047599-5ed78cf3-9590-4c3c-af10-7db982130f0b.png)

### Expected behavior

Everything works, version mismatch and warnings about needing a newer version of betaflight configurator. 

### Configurator version

10.7.2

**Comment by haslinghuis** [comment] 2022-07-31 22:38
Sorry for the inconvenience. It it fixed in nightly builds.
Closing as duplicate of #2978

**Closed by haslinghuis** 2022-07-31 22:38 UTC
Labels: Template: Bug
