### ISSUE TITLE
error can't open configurator

### ISSUE THREAD

**Issue by PIRATES3D** [betaflight/betaflight-configurator#1073] opened 2018-06-23 15:48 UTC
error can't open configurator
![betaflight 10 3](https://user-images.githubusercontent.com/21023153/41811310-2aa6e632-7705-11e8-9f60-ee08b4c13376.jpg)

thanks in advance for the great work.

**Comment by samuelrettore** [comment] 2018-06-23 16:37
I have same problem

**Comment by arierep60** [comment] 2018-06-23 20:55
I have the same error here :(

**Comment by mikeller** [comment] 2018-06-23 22:30
@PIRATES3D, @samuelrettore, @arierep60: A mention of what operating system and version you are using would be real helpful.

**Comment by arierep60** [comment] 2018-06-23 22:44
Windows 10 Home 64 bits

**Comment by AndersHoglund** [comment] 2018-06-23 22:48
Seems to be a lingo issue. Seen other reports, hinting it could be a Spanish or/and Portuguese xlat problem. My English Win10 installation worked flawlessly. Or maybe it worked because I had earlier versions installed, i.e. update works but new installs fail. Just an idea...

**Comment by PIRATES3D** [comment] 2018-06-23 23:53
@mikeller : thanks for the fast answer. I have windows 10 PRO 64bit (Portuguese language) with all the updates installed.

Error message translated: Error loading the extension. Fail at loading the extension from: C:\Program Filles........

Thanks again.

**Comment by mikeller** [comment] 2018-06-23 23:55
@AndersHoglund: Good catch, could be an illegal placeholder (or a character sequence being interpreted as one) in one or more of the language files.


@PIRATES3D, @samuelrettore, @arierep60: Can you please also post what language you are using? For now, the workaround seems to be to switch to English.

**Comment by McGiverGim** [comment] 2018-06-24 07:08
By the error, it seems this phrase `Invalid image size; expected $1×$2 instead of $3×$4` but I'm out of a computer until Tuesday to debug it.

**Comment by binlan** [comment] 2018-06-24 08:21
duplicates #1074

**Comment by mikeller** [comment] 2018-06-24 09:03
Ok, I think I've fixed it (I cannot reproduce it). Please try the configurator builds from https://drive.google.com/drive/folders/1b48TjU2cXBPWrNFA44rOzS3z--txlsw0?usp=sharing, and provide feedback.

**Comment by binlan** [comment] 2018-06-24 09:06
@mikeller does it mean, the workaround with spaces is not needed anymore? (as mentioned in #1074 )

**Comment by mikeller** [comment] 2018-06-24 09:07
Since the strings in question are not used anywhere: No.

**Comment by arierep60** [comment] 2018-06-24 09:30
@McGiverGim did that and now it works! thanks man ;)

**Comment by arierep60** [comment] 2018-06-24 09:31
@PIRATES3D did that and now it works fine, thanks man ;)

**Comment by AndersHoglund** [comment] 2018-06-24 10:40
Would this fix lead to a 10.3.x_maint branch? And a 10.3.1 release? Or should we stay on the "one-track" policy and fix this in the next 10.4.0 release?

**Comment by mikeller** [comment] 2018-06-24 12:00
@AndersHoglund: Yes, I think this will best be fixed / released as 10.3.1 from a maintenance branch, the same way we are doing patch releases for the firmware.

**Comment by GeraldoGarcia** [comment] 2018-06-25 19:31
I am sure @PIRATES3D is using Win10 Brazilian Portuguese version. I had the same problem with the pre-release version from Boris B page and solved it by altering the system default language to English-US.

**Closed** 2018-06-26 10:22 UTC
