### ISSUE TITLE
PID slider issue.

### ISSUE THREAD

**Issue by Kraiwinus** [betaflight/betaflight-configurator#2123] opened 2020-07-14 12:23 UTC
When changing the pid sliders to:
Master: 1.1
Balance 0.5
gain 1.8
response 1.0

then saving, the configurator says you have to enable sliders.
im using btfl 4.2.0 btflconfig 10.7.0

I think it's a rounding issue

**Comment by mikeller** [comment] 2020-07-14 12:41
Duplicate of #2049.

**Closed by mikeller** 2020-07-14 12:41 UTC
