### ISSUE TITLE
Can´t install on Windows 10 x64 

### ISSUE THREAD

**Issue by MtsPac** [betaflight/betaflight-configurator#2649] opened 2021-10-30 00:22 UTC
I tryed to install the 10.7.1 version and it stops at the end of the installation. I've stopped the process and tried to open the betaflight configurator and it worked, but the version was the 10.4.1. Don,t know whats wrong. Tried to unninstall, erase the registration, rebooting. Nothing seems to work. Everytime it stops at the same point and installs the 10.4.1 version.

**Comment by haslinghuis** [comment] 2021-10-30 01:23
Duplicate of #2629

Fixed for 10.8.0

**Comment by Polax83** [comment] 2021-11-14 10:04
Hello, same problems.
When did 10.8.0 release?

**Comment by rwhazlehurst** [comment] 2021-11-19 16:03
Same problem...see screenshot for point where it hangs.
![Capture](https://user-images.githubusercontent.com/6931862/142653510-c8dc4cc4-002f-4048-896d-04892c873476.JPG)
.

**Comment by rwhazlehurst** [comment] 2021-11-19 16:06
> Same problem...see screenshot for point where it hangs. ![Capture](https://user-images.githubusercontent.com/6931862/142653510-c8dc4cc4-002f-4048-896d-04892c873476.JPG) .

Ugg...not 2 minutes after pressing submit on my previous post, I jumped over to the installer to kill the job and it had completed successfully...

**Comment by butcher51** [comment] 2021-11-21 13:46
Yeah same here, installer got stuck.

**Comment by cremymeatballs** [comment] 2021-11-21 19:12
Ive tried several times myself. Mine gets stuck in the exact same spot every time I've let it run for almost two days now and it still hasn't installed what could be the problem?

**Comment by ConnerC579** [comment] 2021-12-26 02:59
![Screenshot (1)](https://user-images.githubusercontent.com/96672299/147397810-7b3a9130-4266-4c6c-a89b-a20e3aad9ba7.png)
I am having this problem. Have tried rebooting and restarting install process.

**Comment by haslinghuis** [comment] 2021-12-26 03:09
We have a 10.8 pre-release. Please check it out: https://github.com/betaflight/betaflight-configurator/releases

Please be aware to update any 4.3 development releases with the latest available firmware.

**Comment by ConnerC579** [comment] 2021-12-26 04:14
Thank you for the response. I was able to install 10.8. I don’t have any
receivers or drones to use yet. But I will soon.

Can you point me to some good beginner resources to learn how to use
betaflight? Right now it’s a foreign language to me. All of it.

**Comment by haslinghuis** [comment] 2021-12-26 04:42
https://github.com/betaflight/betaflight/wiki

**Comment by Bud13420** [comment] 2021-12-29 21:09
> ![Screenshot (1)](https://user-images.githubusercontent.com/96672299/147397810-7b3a9130-4266-4c6c-a89b-a20e3aad9ba7.png) I am having this problem. Have tried rebooting and restarting install process.

Having same issue? How fixed?

**Comment by ConnerC579** [comment] 2021-12-29 22:45
Try this 10.8 version. It installed for me when I had this issue.

https://github.com/betaflight/betaflight-configurator/releases

**Comment by Bud13420** [comment] 2022-01-01 19:45
I did. Thanks brother/sister!

**Closed** 2022-01-19 00:15 UTC
Labels: duplicate
