### ISSUE TITLE
Problem with M1 macbook crashing 

### ISSUE THREAD

**Issue by michael-blue2** [betaflight/betaflight-configurator#2515] opened 2021-06-20 09:40 UTC
When I open the configurator, and I have the quad connected it crashes (photo bellow) and it doesnt even open. When I dont have anything connected to the MacBook then the configurator open up normally. I can then connect the quad. connect to the settings but for a few seconds (max 20s) and then the app it crashes again and i get this error.

I am using a MacBook pro m1 8gb with version 11.4
betaflight configurator is 10.7

<img width="515" alt="Screenshot 2021-06-20 at 12 39 30 PM" src="https://user-images.githubusercontent.com/25118311/122669154-ab242500-d1c4-11eb-9f79-13a99bab6c58.png">

**Comment by haslinghuis** [comment] 2021-06-20 12:11
Duplicate of #2274

**Closed by haslinghuis** 2021-06-20 12:11 UTC

**Comment by haslinghuis** [comment] 2021-06-22 22:41
@michael-blue2 did you check the nightlies build: https://github.com/betaflight/betaflight-configurator-nightlies/releases
