### ISSUE TITLE
Android Version says not newest version

### ISSUE THREAD

**Issue by druckgott** [betaflight/betaflight-configurator#3318] opened 2023-02-05 18:13 UTC
### Describe the bug

Hello, I installed the android version 10.9 but I always get the information that it's not the newest version

### To Reproduce

Install current version on Android (Huawei) 

### Expected behavior

Don't say it's not newest version
![Screenshot_20230205_190903_com betaflight betaflight_configurator_debug](https://user-images.githubusercontent.com/18383738/216837284-65be7729-a0ca-42e2-bdff-e9da5f7b4985.jpg)
![Screenshot_20230205_190930_com betaflight betaflight_configurator_debug](https://user-images.githubusercontent.com/18383738/216837287-2a9a5d4c-2c1b-490c-be1a-7d23cba13f1f.jpg)

### Configurator version

10.9

**Comment by haslinghuis** [comment] 2023-02-05 21:52
Duplicate of #3285

**Closed by haslinghuis** 2023-02-05 21:52 UTC
Labels: Template: Bug
