### ISSUE TITLE
Presets not displaying correctly

### ISSUE THREAD

**Issue by blacktigersoftware** [betaflight/betaflight-configurator#2788] opened 2022-02-01 09:54 UTC
### Describe the bug

Presets not showing CLI / Options /  weird scrolling

![Untitled](https://user-images.githubusercontent.com/251790/151947398-08f1b656-5e3d-48a7-95ba-0bb7cb788af2.png)

### To Reproduce

Connect in "Virtual Mode".  Go to "Presets" tab.  Select All firmwares,   My example was the "Joshua Bardwell rates"  which should have an "unchecked" option.

### Expected behavior

select the option, see the CLI

### Configurator version

10.8.0 (c9b7ed8f)

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```
virtual default

**Comment by haslinghuis** [comment] 2022-02-01 12:23
Duplicate of https://github.com/betaflight/betaflight-configurator/issues/2774

Fixed in RC. Please upgrade to https://github.com/betaflight/betaflight-configurator/releases/tag/10.8.0-RC3

**Closed by haslinghuis** 2022-02-01 12:23 UTC
