### ISSUE TITLE
Problem on Mac

### ISSUE THREAD

**Issue by DylanBailey09** [betaflight/betaflight-configurator#2914] opened 2022-05-05 23:52 UTC
### Describe the bug

when try to launch Betaflight it says that it can't verify the creator and it thinks its malware 

### To Reproduce

I just have to try and launch Betaflight again

### Expected behavior

I expected it to launch without a problem

### Configurator version

10.8.0

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```

**Comment by haslinghuis** [comment] 2022-05-06 00:10
Duplicate of https://github.com/betaflight/betaflight-configurator/issues/2902

**Closed by haslinghuis** 2022-05-06 00:10 UTC
Labels: Template: Bug
