### ISSUE TITLE
Reciever Tab model preview not responding. 

### ISSUE THREAD

**Issue by El-Takanashi** [betaflight/betaflight-configurator#3868] opened 2024-04-01 07:08 UTC
### Describe the bug

Even though the channel bars respond correctly to stick/switch inputs, the preview of the model does not move at all. Hakrc f722v2 and SpeedyBee f405v3. reverting to 10.9 shows model preview move correctly.

### To Reproduce

Power radio. Connect to config 10.10.0 r3. Go to receiver tab,  move sticks - observe bars move correctly, but not model preview at all.

### Expected behavior

model preview to move in accordance with stick inputs/channel bars

### Configurator version

10.10.0

**Comment by haslinghuis** [comment] 2024-04-01 11:05
Duplicate of #3853

**Comment by haslinghuis** [comment] 2024-04-29 17:55
- Please use configurator [release](https://github.com/betaflight/betaflight-configurator/releases/tag/10.10.0)
- Should be fixed in #3847

**Comment by El-Takanashi** [comment] 2024-05-03 01:46
Thanks

**Closed** 2024-05-03 08:52 UTC
Labels: Template: Bug
