### ISSUE TITLE
Bluetooth and Wifi serial comunication

### ISSUE THREAD

**Issue by MarcinKnD** [betaflight/betaflight-configurator#3014] opened 2022-09-01 17:45 UTC
### Is your feature request related to a problem? Please describe

A great idea is to extend BetaFlight Configurator with connectivity via BT and WiFi SERIAL. Modules such as ESP01s are small, light and with ESPlink software installed, they act as a WIFI bridge to the serial. The connection is very simple, only no support in the configurator. While Virtual Com can be helped on a PC, it is not possible on an Android phone. Make it possible to connect via SERIAL WIFI and BT

### Describe the solution you'd like

Support for SERIAL WIFI and SERIAL Bluetooth connection

### Describe alternatives you've considered

no more usb cable

wouldn't that be great

**Comment by Hawxxer** [comment] 2022-09-02 12:14
Related to this https://github.com/betaflight/betaflight-configurator/issues/466 
Looks like normal bluetooth already works.

**Comment by haslinghuis** [comment] 2022-09-05 20:31
Duplicate of #466

**Closed by haslinghuis** 2022-09-05 20:31 UTC
Labels: Template: Feature Request
