### ISSUE TITLE
3.2.1, cant download bb-log

### ISSUE THREAD

**Issue by kajsilander78** [betaflight/betaflight-configurator#611] opened 2017-08-13 12:51 UTC
Since upgrade from 3.1.3 to 3.2.1 I cant download blackbox files. Results in 0 byte files.
Works fine again after downgrade....
My FC is SPF3. Betaflight 3.2 RC1

**Comment by mikeller** [comment] 2017-08-13 12:55
Duplicate of #606.

**Closed by mikeller** 2017-08-13 12:55 UTC
Labels: duplicate
