### ISSUE TITLE
Cant install on Catalina

### ISSUE THREAD

**Issue by Letzrock** [betaflight/betaflight-configurator#1735] opened 2019-10-11 17:39 UTC
I tried using sudo spctl --master-disable and it still won't run.

**Comment by Docteh** [comment] 2019-10-11 19:30
Is Catalina out yet? I've been waiting for it to be fully out to investigate the signing issues we've been seeing.

**Comment by Letzrock** [comment] 2019-10-11 19:42
Yes I installed it 2 days ago

**Comment by mikeller** [comment] 2019-10-12 20:31
Closing as duplicate of #1367 

@Letzrock: For next time, please have a look if there is an existing issue for your problem before opening a new one.

**Closed by mikeller** 2019-10-12 20:31 UTC

**Comment by philcal** [comment] 2019-11-09 08:15
@mikeller
Issue #1367 has no mention of Catalina. It appears this is _not_ a duplicate of that issue.

**Comment by Docteh** [comment] 2019-11-09 09:20
@philcal #1675 is probably worth a look

**Comment by mikeller** [comment] 2019-11-10 00:13
@philcal: Sorry, my bad. No idea how I got to `#1367` when meaning to type #1675.
